Update privateGPT.py to work with python 3.8
Error: With python 3.8 we get error:
    match model_type:
          ^
SyntaxError: invalid syntax

Reason: The match/case syntax, otherwise known as Structural Pattern Matching, was only introduced in Python version 3.10.

Updated the code to not use match.